glemping/urls.py
from django.urls import path
from . import views

app_name = 'glemping'

urlpatterns = [
    path('', views.homepage_view, name='home'),
    path('news/', views.post_list, name='post_list'),
    path('news/<slug:post>/', views.post_detail, name='post_detail'),
    path('activities/', views.activity_list, name='activity_list'),
    path('gallery/', views.gallery_list, name='gallery_list'),
    path('reviews/', views.review_view, name='reviews'),
    path('about/', views.about, name='about'),
    path('booking/', views.booking, name='booking'),
]

kraces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from glemping import views as glemping_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('glemping.urls', namespace='glemping')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

glemping/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20,
                              choices=STATUS_CHOICES, default='draft')
    image = models.ImageField(blank=True)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('glemping:post_detail', args=[self.slug])


class Activity(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(blank=True)
    season = models.CharField(max_length=100)
    status = models.CharField(max_length=20,
                              choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    publish = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Picture(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=100)
    image = models.ImageField()

    status = models.CharField(max_length=20,
                              choices=STATUS_CHOICES, default='draft')
    publish = models.DateTimeField(default=timezone.now)
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


class Review(models.Model):

    name = models.CharField(max_length=50)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    rating = models.CharField(max_length=5, default='5')

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Review by {self.name}'


class Reservation(models.Model):
    name = models.CharField(max_length=20, default='')
    surname = models.CharField(max_length=20, default='')
    phone_number = models.CharField(max_length=8, default='')
    email = models.EmailField(default='')
    date = models.DateField(default=timezone.now)
    available = models.BooleanField(default=True)

    class Meta:
        unique_together = ("date", "available")

    def __str__(self):
        return f'{self.name} {self.surname} on {self.date}'

glemping/forms.py
from django.forms import ModelForm
from .models import Review, Reservation
from django import forms


class ReviewForm(ModelForm):
    RATING_CHOICES = (
        ('★☆☆☆☆', '★☆☆☆☆'),
        ('★★☆☆☆', '★★☆☆☆'),
        ('★★★☆☆', '★★★☆☆'),
        ('★★★★☆', '★★★★☆'),
        ('★★★★★', '★★★★★')
    )
    rating = forms.ChoiceField(
        choices=RATING_CHOICES, widget=forms.RadioSelect())

    class Meta:
        model = Review
        fields = ('rating', 'name', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'body': forms.Textarea(attrs={'placeholder': 'Enter review here..'}),
        }


class ReservationForm(ModelForm):

    class Meta:
        model = Reservation
        fields = ('name', 'surname', 'phone_number', 'email', 'date')
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'})
        }

glemping/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Activity, Picture, Review, Reservation
from .forms import ReviewForm, ReservationForm
from django.db import IntegrityError


def homepage_view(request):
    posts = Post.published.all()
    activities = Activity.published.all()
    reviews = Review.objects.all()[:3]
    pictures = Picture.objects.all()[:4]
    return render(request,
                  'glemping/home.html',
                  {'section': 'home',
                   'posts': posts,
                   'activities': activities,
                   'reviews': reviews,
                   'pictures': pictures})


def post_list(request):
    posts = Post.published.all()
    return render(request,
                  'glemping/news/list.html',
                  {'posts': posts, 'section': 'news'})


def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    return render(request, 'glemping/news/detail.html', {'post': post, 'section': 'news'})


def activity_list(request):
    activities = Activity.published.all()
    return render(request,
                  'glemping/activities/list.html',
                  {'activities': activities,
                   'section': 'activities'})


def gallery_list(request):
    pictures = Picture.published.all()
    return render(request,
                  'glemping/gallery/list.html',
                  {'pictures': pictures,
                   'section': 'gallery'})


def review_view(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save(commit=True)
            reviews = Review.objects.all()
            return render(request,
                          'glemping/reviews/review_added.html',
                          {'section': 'reviews', 'reviews': reviews})
    else:
        review_form = ReviewForm()

    reviews = Review.objects.all()
    return render(request,
                  'glemping/reviews/review.html',
                  {'review_form': review_form, 'reviews': reviews, 'section': 'reviews'})


def booking(request):
    if request.method == 'POST':
        reservation_form = ReservationForm(request.POST)
        try:
            if reservation_form.is_valid():
                reservation_form.save(commit=True)
                Reservation.available = False

                return render(request,
                              'glemping/booking/success.html',
                              {'section': 'booking'})
        except IntegrityError:
            return render(request,
                          'glemping/booking/error.html',
                          {'section': 'booking'})

    else:
        reservation_form = ReservationForm()
        return render(request,
                      'glemping/booking/booking.html',
                      {'section': 'booking', 'reservation_form': reservation_form})


def about(request):
    return render(request, 'glemping/about/about_us.html', {'section': 'about'})

glemping/templates/glemping/about/about_us.html
{% extends 'glemping/base.html' %}
{% block title %}About us{% endblock title %}
{% block content %}
<div class="about-us">
    <div class="map">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2175.0788399569083!2d22.366882002110305!3d56.964581980801!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46efc9c508e92ca7%3A0x9e61c4f1b96db697!2sKabile%20parish!5e0!3m2!1sen!2suk!4v1612029829482!5m2!1sen!2suk&z=2"
            width="600" height="400" frameborder="0" style="border:3px black solid;" allowfullscreen=""
            aria-hidden="false" tabindex="0"></iframe>
    </div>
    <div class="about">
        <h1>About us</h1>
        <p>Do you want to camp under a starry sky,
            but still enjoy comfort?
            Come to us and watch the stars in the fresh air without getting out of bed,
            but still feeling like in a tent.</p>
    </div>
</div>
{% endblock content %}

glemping/templates/glemping/activities/list.html
{% extends 'glemping/base.html' %}
{% block title %}
Activities
{% endblock title %}

{% block content %}
<h1>Activities</h1>
<div class="activities">
    {% for activity in activities %}
    <div class="activity">
        <h2>{{activity.title}}</h2>
        <br>
        <img src="{{activity.image.url}}" width="30%" class="grid-image">
        <p>{{activity.description}}</p>
    </div>
    {% endfor %}
</div>

{% endblock content %}

glemping/templates/glemping/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/glemping.css' %}" rel="stylesheet">
</head>

<body>
    <header>
        <div class="hero-image">
            <div class="hero-text">
                <img src="/static/kraces-logo-3.png">
            </div>

        </div>
        <div class="topnav">
            <div class="navbar">
                <a {% ifequal section 'home' %} class="active" {% endifequal %}
                    href="{% url 'glemping:home' %}">Home</a>
                <a {% ifequal section 'news' %} class="active" {% endifequal %}
                    href="{% url 'glemping:post_list' %}">News</a>
                <a {% ifequal section 'activities' %} class="active" {% endifequal %}
                    href="{% url 'glemping:activity_list' %}">Activities</a>
                <a {% ifequal section 'booking' %} class="active" {% endifequal %}
                    href="{% url 'glemping:booking' %}">Reserve</a>
                <a {% ifequal section 'gallery' %} class="active" {% endifequal %}
                    href="{% url 'glemping:gallery_list' %}">Gallery</a>
                <a {% ifequal section 'reviews' %} class="active" {% endifequal %}
                    href="{% url 'glemping:reviews' %}">Reviews</a>
                <a {% ifequal section 'about' %} class="active" {% endifequal %} href="{% url 'glemping:about' %}">About
                    us</a>
            </div>
        </div>
    </header>
    <content>
        {% block content %}
        {% endblock content %}
    </content>
    <footer>
        <div id="footer-2">
            <h1>Quicklinks</h1>
            <ul>
                <li><a href="{% url 'glemping:post_list' %}">News</a></li>
                <li><a href="{% url 'glemping:activity_list' %}">Activities</a></li>
                <li><a href="{% url 'glemping:booking' %}">Book Now</a></li>
                <li><a href="{% url 'glemping:gallery_list' %}">Gallery</li>
                <li><a href="{% url 'glemping:reviews' %}">Reviews</a></li>
            </ul>
        </div>
        <div id="footer-3">
            <h1>Contacts</h1>
            <ul>
                <li>Call: +371 22 430 265</li>
                <li>ingus.hartmanis@inbox.lv</li>
                <li>Kuldigas novads,
                    Kabiles pagasts,
                    Krāces </li>
                <div id="social">
                    <li><a href="https://www.facebook.com/glempingsKraces"><img src="/static/facebook-icon.png"></a>
                    </li>
                    <li><a href="#"><img src="/static/instagram-icon.png"></a></li>
                    <li><a href="#"><img src="/static/twitter-icon.png"></a></li>
                </div>

            </ul>
        </div>

        <div id="footer-1">
            <img src="/static/kraces-logo-3.png">
        </div>
    </footer>


</body>

</html>

glemping/templates/glemping/booking/booking.html
{% extends 'glemping/base.html' %}

{% block title %}Book now{% endblock title %}

{% block content %}
<div id="booking-page">
    <form method="POST">
        <div id="booking-form">
            {{reservation_form.as_p}}
            {% csrf_token %}
            <p id="submit-button"><input type="submit" value="Book"></p>
        </div>
    </form>
</div>
{% endblock content %}

glemping/templates/glemping/booking/error.html
{% extends 'glemping/base.html' %}

{% block title %}This date is not available{% endblock title %}

{% block content %}

<h1>Sorry, someone already booked this date</h1>

{% endblock content %}

glemping/templates/glemping/booking/success.html
{% extends 'glemping/base.html' %}

{% block title %}Success{% endblock title %}

{% block content %}
<h1>Your booking has been successful, We'll email You details</h1>
{% endblock content %}

glemping/templates/glemping/gallery/list.html
{% extends 'glemping/base.html' %}

{% block title %}Gallery{% endblock title %}
{% block content %}
<div class="gallery">
    {% for picture in pictures %}
    <img src="{{picture.image.url}}" class="picture">
    {% endfor %}
</div>
{% endblock content %}

glemping/templates/glemping/home.html
{% extends 'glemping/base.html' %}

{% block title %}Kraces{% endblock title %}
{% block content %}

<div id="landing">
    <div id="landing-text">
        <p>Do you want to camp under a starry sky,
            but still enjoy comfort?
            Come to us and watch the stars in the fresh air without getting out of bed,
            but still feeling like in a tent.
        </p>
    </div>
    <img src="/static/landing-bg.jpg" width="100%">

</div>

{% endblock content %}

glemping/templates/glemping/news/detail.html
{% extends 'glemping/base.html' %}
{% block title %} {{post.title}} {% endblock title %}

{% block content %}
<h1>{{post.title}}</h1>
<p>{{post.body}}</p>
<img src="{{post.image.url}}" width="50%">
<br>
<p>{{post.publish}}</p>
{% endblock content %}

glemping/templates/glemping/news/list.html
{% extends 'glemping/base.html' %}
{% load static %}
{% block title %}News{% endblock title %}

{% block content %}
<h1>News</h1>
<div id="news">
    {% for post in posts %}
    <div id="news-list">
        <a href="{{ post.get_absolute_url }}">
            <h2>{{post.title}}</h2>
            <br>
            <img src="{{post.image.url}}" width="25%">

            <p class="date">Published {{post.publish}}</p>
            <p>
                {{post.body|truncatewords:30|linebreaks}}
            </p>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock content %}

glemping/templates/glemping/rating.html
<form class="rating">
    <label>
        <input type="radio" name="stars" value="1" />
        <span class="icon">★</span>
    </label>
    <label>
        <input type="radio" name="stars" value="2" />
        <span class="icon">★</span>
        <span class="icon">★</span>
    </label>
    <label>
        <input type="radio" name="stars" value="3" />
        <span class="icon">★</span>
        <span class="icon">★</span>
        <span class="icon">★</span>
    </label>
    <label>
        <input type="radio" name="stars" value="4" />
        <span class="icon">★</span>
        <span class="icon">★</span>
        <span class="icon">★</span>
        <span class="icon">★</span>
    </label>
    <label>
        <input type="radio" name="stars" value="5" />
        <span class="icon">★</span>
        <span class="icon">★</span>
        <span class="icon">★</span>
        <span class="icon">★</span>
        <span class="icon">★</span>
    </label>
</form>

glemping/templates/glemping/reviews/review.html
{% extends 'glemping/base.html' %}

{% block title %}Reviews{% endblock title %}

{% block content %}
<div class="reviews">
    <h1>What people say about us</h1>
    {% for review in reviews %}
    <div class="review">
        <h2>{{review.name}}</h2>
        <div id="review-rating">
            <p>{{review.rating}}</p>
        </div>
        <p>{{review.body|linebreaks}}</p>
    </div>
    {% endfor %}
</div>
<h1>Add a review</h1>

<form method="POST">
    <div id="review_form">
        <div id="review-rating" value="name">
            {{review_form.rating}}
        </div>
        <div id="review-name">
            {{review_form.name}}
        </div>
        <div id="review-body">
            {{review_form.body}}
        </div>
    </div>
    {% csrf_token %}
    <p><input type="submit" value="Add review"></p>
</form>

{% endblock content %}

glemping/templates/glemping/reviews/review_added.html
{% extends 'glemping/base.html' %}

{% block title %} Thank You {% endblock title %}

{% block content %}
<h1>Thank You, review has been added</h1>
{% for review in reviews %}
<div class="review">
    <h2>{{review.name}}</h2>
    <div id="review-rating">
        <p>{{review.rating}}</p>
    </div>
    <p>{{review.body}}</p>
</div>
{% endfor %}
{% endblock content %}